{"createdAt":{"$$date":1617783710061},"type":"text","raw":"{\"@timestamp\": \"2021-04-07T11:21:45.791621\", \"event\": {\"action\": \"aspsp-request-oauth-token\", \"category\": \"process\", \"message\": \"Failed to replace code with token\", \"labels\": {\"application\": \"aggregate\", \"env\": \"server.settings\"}, \"kind\": \"event\"}, \"host\": {\"architecture\": \"x86_64\", \"kind\": \"host\"}, \"logline\": {\"level\": \"ERROR\", \"kind\": \"logline\"}, \"destination\": {\"domain\": \"openbankingsb.poalim-api.co.il\"}, \"network\": {\"direction\": \"egress\", \"protocol\": \"https\"}, \"url\": {\"domain\": \"openbankingsb.poalim-api.co.il\", \"original\": \"https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/oauth2/v1/token\", \"path\": \"/xs2a/unpr/oauth2/v1/token\", \"params\": \"\", \"port\": 19443}, \"trace\": {\"id\": \"ft5J8vfrnU0p9lEpTlMV5V4dAeIkeIJ6\"}, \"transaction\": {\"id\": \"1c799217-1b77-44ff-b3ac-107df83cfeeb\"}, \"user\": {\"id\": \"poa16\"}, \"log\": {\"logger\": \"aggregate.auth_processes\", \"origin\": {\"function\": \"mark_auth_process_as_successful\", \"file\": {\"line\": 99, \"name\": \"auth_processes.py\"}}}, \"labels\": {\"task\": \"web\", \"aspsp\": \"12\"}, \"process\": {\"pid\": 19}, \"error\": {\"message\": \"AspspError: Request {'event.action': 'aspsp-request-oauth-token', 'span.id': '6fca161c-de5a-4020-9053-24fa9df964a6', 'destination': {'domain': 'openbankingsb.poalim-api.co.il'}, 'network': {'direction': 'egress', 'protocol': 'https'}, 'url': {'domain': 'openbankingsb.poalim-api.co.il', 'original': 'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/oauth2/v1/token', 'path': '/xs2a/unpr/oauth2/v1/token', 'params': '', 'port': 19443}, 'http.request.method': 'POST'} to ASPSP 12 returned statusCode=None content=None\", \"type\": \"AspspError\", \"stack_trace\": \"  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 384, in _make_request\\n    six.raise_from(e, None)\\n  File \\\"<string>\\\", line 2, in raise_from\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 380, in _make_request\\n    httplib_response = conn.getresponse()\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 1347, in getresponse\\n    response.begin()\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 307, in begin\\n    version, status, reason = self._read_status()\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 268, in _read_status\\n    line = str(self.fp.readline(_MAXLINE + 1), \\\"iso-8859-1\\\")\\n  File \\\"/usr/local/lib/python3.9/socket.py\\\", line 704, in readinto\\n    return self._sock.recv_into(b)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/gevent/_ssl3.py\\\", line 567, in recv_into\\n    return self.read(nbytes, buffer)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/gevent/_ssl3.py\\\", line 390, in read\\n    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 313, in gevent._gevent_c_hub_primitives._primitive_wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 314, in gevent._gevent_c_hub_primitives._primitive_wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_waiter.py\\\", line 154, in gevent._gevent_c_waiter.Waiter.get\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_gevent_c_greenlet_primitives.pxd\\\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch\\nsocket.timeout: The read operation timed out\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/adapters.py\\\", line 439, in send\\n    resp = conn.urlopen(\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 637, in urlopen\\n    retries = retries.increment(method, url, error=e, _pool=self,\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/util/retry.py\\\", line 368, in increment\\n    raise six.reraise(type(error), error, _stacktrace)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/packages/six.py\\\", line 686, in reraise\\n    raise value\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 597, in urlopen\\n    httplib_response = self._make_request(conn, method, url,\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 386, in _make_request\\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 306, in _raise_timeout\\n    raise ReadTimeoutError(self, url, \\\"Read timed out. (read timeout=%s)\\\" % timeout_value)\\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out. (read timeout=10)\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 251, in make_aspsp_request\\n    res = _make_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 176, in _make_request\\n    res = request_func(url, timeout=ASPSP_REQUEST_TIMEOUT, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 581, in post\\n    return self.request('POST', url, data=data, json=json, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 533, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 646, in send\\n    r = adapter.send(request, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/adapters.py\\\", line 529, in send\\n    raise ReadTimeout(e, request=request)\\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out. (read timeout=10)\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/src/server/aggregate/auth_processes.py\\\", line 95, in mark_auth_process_as_successful\\n    access_token = xs2a.consents.get_access_token(\\n  File \\\"/usr/src/server/aggregate/xs2a/consents.py\\\", line 164, in get_access_token\\n    res = fetch.make_aspsp_post_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 308, in make_aspsp_post_request\\n    return make_aspsp_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 263, in make_aspsp_request\\n    raise AspspError(aspsp_code, tag, req_logging_details, None, None) from e\\n\", \"cause\": {\"error\": {\"message\": \"HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out. (read timeout=10)\", \"type\": \"ReadTimeout\"}}, \"code\": \"FAILED_TO_REPLACE_CODE_WITH_TOKEN\"}, \"span\": {\"id\": \"6fca161c-de5a-4020-9053-24fa9df964a6\"}, \"http\": {\"request\": {\"method\": \"POST\"}, \"response\": {\"status_code\": null, \"body\": {\"content\": null}}}}","hash":"728c00e986dcef6cd0195cbda416f257569137cf","_id":"0KkTBYC3bv4yq7Ch"}
{"createdAt":{"$$date":1617716418184},"type":"text","raw":"sha-256","hash":"df3f0eecf32de5413d72f23b7632063a9ee7a585","_id":"1x2n0QHEDH7VEyE9"}
{"createdAt":{"$$date":1617784229492},"type":"text","raw":"/xs2a/unpr/v1.0.5/consents/0808fb65-be2a-dda9-0cf9-50ddebc7fa67","hash":"d20c8cb5d892e7fac0bd49dbe6bcd948ac23d9f5","_id":"2osX3CHUg4GwCyjd"}
{"createdAt":{"$$date":1617784764167},"type":"text","raw":"    \"size\": 1000\n","hash":"560e201285ff359015b914664106c577a87b8228","_id":"6FiSjgACbFbxyMU7"}
{"createdAt":{"$$date":1617717217915},"type":"text","raw":"ASPSP_REQUEST_TIMEOUT","hash":"e2298d5e3ec64e8068e3846182812d53cb760d3e","_id":"7HMDlDojDaK4oG8A"}
{"createdAt":{"$$date":1617716461375},"type":"text","raw":"f'keyId=\"{key_id}\",algorithm=\"rsa-sha256\",headers=\"{header_list}\",signature=","hash":"c897cc75179281f3598b2f69ec819dbd467bd646","_id":"8cwu8ZTMbJAE1c89"}
{"createdAt":{"$$date":1617784261617},"type":"text","raw":"200200202","hash":"e4db852dbe063225299498d7d8d237baffad98de","_id":"9Ee7CNzM9jcz477h"}
{"createdAt":{"$$date":1617716964718},"type":"text","raw":"https://aws.amazon.com/blogs/aws/elb-idle-timeout-control/","hash":"d8dc3357f25c05c147dfb4cf6714f589207926c3","_id":"AmBXQke7p9wsAVfq"}
{"createdAt":{"$$date":1617783673859},"type":"text","raw":"300600103","hash":"29d4562b98314c2b38d69d73898986cce216eeec","_id":"BLYIg4uj9xyN9F5A"}
{"createdAt":{"$$date":1617716262503},"type":"text","raw":"scaRedirect","hash":"5b58e391e8ec54345f7a8bb4b28ba3c822b30a90","_id":"BhQpYLpSxZPou2Ml"}
{"createdAt":{"$$date":1617782855603},"type":"text","raw":"1\"}, \"log\": {\"logger\": \"django.request\", \"origin\": {\"function\": \"log_response\", \"file\": {\"line\": 224, \"name\": \"log.py\"}}}, \"labels\": {\"task\": \"web\"},","hash":"675e8d6121c6a7cff834762d2496412db1ce855b","_id":"BrxV4ACjTxFdqHI1"}
{"createdAt":{"$$date":1617783708043},"type":"text","raw":"UfE35FzhcoAPTY-I1Evw0QLj5JZey8B3IGtuyl7J-fQ5-Pe_IbQxd9vCdW5LiTRZ-WZAN85BZy7KlRQxMOhe6mVmT_gMv-2Il4AoRAJv127r5RKWwGmzPLj61vcYEYzdvGL6gXk1bPRbO0AtB6FvfP3tACK-ShAM73ZWVmeNBvT3_zwRxXfc_6i9Udi536jLEBzScTgkOJbd5r5i8dS1pduacPZKB0dPYiTEXxXn25QXDYsKh6xnNPhySRImYbxt","hash":"1787d97fba4a329d7ffefb4468fea8ddc5fa8d99","_id":"DbnzrJkqRDIFK2lL"}
{"createdAt":{"$$date":1617784186292},"type":"text","raw":"original","hash":"d73ef92426f2b11dfc4aed4d4bfc41c49ee1087c","_id":"E0BIZGz7eKhpqsdJ"}
{"createdAt":{"$$date":1617784707581},"type":"text","raw":"curl 'https://api.ipify.org?format=json'","hash":"5980b43fa7c709893b4e2ce44f3b48ea7a2e4d87","_id":"EKPVjMfHTwAUsFNX"}
{"createdAt":{"$$date":1617784077783},"type":"text","raw":"statusCode=429 content=b\\'\\\\n            { \"tppMessages\": [{\\\\n                    \"category\": \"ERROR\",\\\\n                    \"code\": \"ACCESS_EXCEEDED\",\\\\n                    \"text\": \"The access on the account has been exceeding the consented multiplicity without PSU involvement per day.\"\\\\n                    }]\\\\n            }\\\\n            \\'')","hash":"d50488ef7abec6b887c736dbc77ea0e350aa80e9","_id":"GFcuvzvtZonGMqTG"}
{"createdAt":{"$$date":1617783543271},"type":"text","raw":"digest: sha-256=47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=\nx-request-id: ca4e6943-7299-40db-84bd-cdbbb893df87\n/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py:842: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings","hash":"ae18a426693d1fbdc843aee2241fb8edf2bbc070","_id":"IeeS0k20eUxviTyV"}
{"createdAt":{"$$date":1617784188305},"type":"text","raw":"aggregate.exceptions.AspspError: AspspError: Request {'event.action': 'aspsp-request-account-balances', 'span.id': 'c694cd61-19bc-49f5-bac5-5ad8c812badb', 'destination': {'domain': 'openbankingsb.poalim-api.co.il'}, 'network': {'direction': 'egress', 'protocol': 'https'}, 'url': {'domain': 'openbankingsb.poalim-api.co.il', 'original': 'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/accounts/55555_142/balances', 'path': '/xs2a/unpr/v1.0.5/accounts/55555_142/balances', 'params': '', 'port': 19443}, 'http.request.method': 'GET'} to ASPSP 12 returned statusCode=429 content=b'\\n            { \"tppMessages\": [{\\n                    \"category\": \"ERROR\",\\n                    \"code\": \"ACCESS_EXCEEDED\",\\n                    \"text\": \"The access on the account has been exceeding the consented multiplicity without PSU involvement per day.\"\\n                    }]\\n            }\\n            '","hash":"f97b8d6f2b3f0d93bdbd2e2c73207a577a4a8dba","_id":"IrhNo8yBu8EPOnQg"}
{"createdAt":{"$$date":1617716984822},"type":"text","raw":"service/backend-service","hash":"e543ca3302de672c8319892d0f1057a1f9347545","_id":"LASHh4W8zHdgFMW0"}
{"createdAt":{"$$date":1617783709053},"type":"text","raw":"{\"@timestamp\": \"2021-04-07T11:21:45.806169\", \"event\": {\"action\": \"django.request\", \"category\": \"web\", \"message\": \"OK: /ui/oauth/callback/mobile/\", \"labels\": {\"application\": \"aggregate\", \"env\": \"server.settings\"}, \"kind\": \"event\", \"duration\": 10041440316}, \"host\": {\"architecture\": \"x86_64\", \"kind\": \"host\"}, \"url\": {\"path\": \"/ui/oauth/callback/mobile/\", \"domain\": \"aggp.feezback.com\", \"kind\": \"url\", \"query\": \"state=UfE35FzhcoAPTY-I1Evw0QLj5JZey8B3IGtuyl7J-fQ5-Pe_IbQxd9vCdW5LiTRZ-WZAN85BZy7KlRQxMOhe6mVmT_gMv-2Il4AoRAJv127r5RKWwGmzPLj61vcYEYzdvGL6gXk1bPRbO0AtB6FvfP3tACK-ShAM73ZWVmeNBvT3_zwRxXfc_6i9Udi536jLEBzScTgkOJbd5r5i8dS1pduacPZKB0dPYiTEXxXn25QXDYsKh6xnNPhySRImYbxt&code=gIoyuHGL\"}, \"source\": {\"ip\": \"147.234.102.176\", \"kind\": \"source\"}, \"client\": {\"bytes\": 0, \"address\": \"147.234.102.176\", \"ip\": \"147.234.102.176\", \"domain\": \"aggp.feezback.com\", \"kind\": \"client\"}, \"useragent\": {\"original\": \"okhttp/4.9.0\", \"kind\": \"useragent\"}, \"user\": {\"kind\": \"user\", \"id\": \"poa16\"}, \"logline\": {\"level\": \"INFO\", \"kind\": \"logline\"}, \"trace\": {\"id\": \"ft5J8vfrnU0p9lEpTlMV5V4dAeIkeIJ6\"}, \"transaction\": {\"id\": \"1c799217-1b77-44ff-b3ac-107df83cfeeb\"}, \"log\": {\"logger\": \"django.request\", \"origin\": {\"function\": \"log_response\", \"file\": {\"line\": 224, \"name\": \"log.py\"}}}, \"labels\": {\"task\": \"web\"}, \"process\": {\"pid\": 19}, \"http\": {\"request\": {\"method\": \"GET\", \"body_bytes\": 0, \"kind\": \"httprequest\"}, \"response\": {\"status_code\": \"200\", \"kind\": \"httpresponse\"}}}","hash":"b50a6552816d14b95dc01698babf4a539a6bf732","_id":"ObeYic0VAhRNkNB3"}
{"createdAt":{"$$date":1617716530689},"type":"text","raw":"deterministic_part","hash":"290efc216d6e47af955eef1042142cb63cb90022","_id":"OxBAm0q4glLlOVAA"}
{"createdAt":{"$$date":1617784230497},"type":"text","raw":"aggregate.exceptions.AspspError: AspspError: Request {'event.action': 'aspsp-request-consent-delete', 'span.id': 'a3dc0c40-d15e-4feb-9e82-455544d7e186', 'destination': {'domain': 'openbankingsb.poalim-api.co.il'}, 'network': {'direction': 'egress', 'protocol': 'https'}, 'url': {'domain': 'openbankingsb.poalim-api.co.il', 'original': 'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/consents/0808fb65-be2a-dda9-0cf9-50ddebc7fa67', 'path': '/xs2a/unpr/v1.0.5/consents/0808fb65-be2a-dda9-0cf9-50ddebc7fa67', 'params': '', 'port': 19443}, 'http.request.method': 'DELETE'} to ASPSP 12 returned statusCode=None content=None","hash":"0756aa65809169fe0943033db131c4bfb8f4db2e","_id":"SmHUeVnZrHzjXbqt"}
{"createdAt":{"$$date":1617784138066},"type":"text","raw":"https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/accounts/55555_142/balances","hash":"d6ece0ae0c92c7e6a22547e55622ad0c6b355747","_id":"TuMngaBicmyBo13h"}
{"createdAt":{"$$date":1617783810531},"type":"text","raw":"19443/xs2a/unpr/v1.0.5/accounts/55555_108/balances\\","hash":"485961dd66a5eb716cc5b57de3c7075a6e2d16ba","_id":"Vh2rQM7S0KByYc7G"}
{"createdAt":{"$$date":1617784209396},"type":"text","raw":"Message: AspspError('AspspError: Request {\\'event.action\\': \\'aspsp-request-account-balances\\', \\'span.id\\': \\'c694cd61-19bc-49f5-bac5-5ad8c812badb\\', \\'destination\\': {\\'domain\\': \\'openbankingsb.poalim-api.co.il\\'}, \\'network\\': {\\'direction\\': \\'egress\\', \\'protocol\\': \\'https\\'}, \\'url\\': {\\'domain\\': \\'openbankingsb.poalim-api.co.il\\', \\'original\\': \\'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/accounts/55555_142/balances\\', \\'path\\': \\'/xs2a/unpr/v1.0.5/accounts/55555_142/balances\\', \\'params\\': \\'\\', \\'port\\': 19443}, \\'http.request.method\\': \\'GET\\'} to ASPSP 12 returned statusCode=429 content=b\\'\\\\n            { \"tppMessages\": [{\\\\n                    \"category\": \"ERROR\",\\\\n                    \"code\": \"ACCESS_EXCEEDED\",\\\\n                    \"text\": \"The access on the account has been exceeding the consented multiplicity without PSU involvement per day.\"\\\\n                    }]\\\\n            }\\\\n            \\'')","hash":"db172e71638f00813edd233e88382c1050ee479b","_id":"Yi0pZnNUFV7CpNHE"}
{"createdAt":{"$$date":1617783811538},"type":"text","raw":"multiplicity","hash":"05682d99b708d051152507fef920f1f53d926369","_id":"ZO9vBEudav1W3DuB"}
{"createdAt":{"$$date":1617716536727},"type":"text","raw":"Signature","hash":"2f32be1dc74166373c988ec03b0bd86f0a576919","_id":"ZiAZ2qpZzpRS3pMM"}
{"createdAt":{"$$date":1617716983810},"type":"text","raw":"LoadBalancer","hash":"ab77a5c72508dcf67636b403d742f337208193ff","_id":"aLXdpZCIZjkwMsTh"}
{"createdAt":{"$$date":1617784347933},"type":"text","raw":"/xs2a/unpr/v1.0.5/accounts/55555_152/balances\\","hash":"265d6e115e344ea180aab99881b685dd7507f2ee","_id":"aU4XCkrJz3LgawlK"}
{"createdAt":{"$$date":1617783541255},"type":"text","raw":"47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU","hash":"82c270a6891a41625f863b0287fe8aada4b210c6","_id":"b7isrQZ9zmT0Xt60"}
{"createdAt":{"$$date":1617784114960},"type":"text","raw":"{\"@timestamp\": \"2021-04-07T08:26:47.031Z\", \"event\": {\"action\": \"aggregate.client_logging\", \"category\": \"process\", \"message\": \"\", \"labels\": {\"application\": \"aggregate-ui\", \"env\": \"production\", \"platform\": \"android\"}, \"kind\": \"event\"}, \"host\": {\"architecture\": \"x86_64\", \"kind\": \"host\"}, \"logline\": {\"level\": \"error\", \"kind\": \"logline\"}, \"ecs\": {\"version\": \"1.6.0\"}, \"user\": {\"id\": \"poa20\"}, \"error\": {\"message\": \"Fetch response was failed due an unknown error (specific error can be found in TPP's logs)\", \"stack_trace\": \"Error: Fetch response was failed due an unknown error (specific error can be found in TPP's logs)\\n    at Mu (<anonymous>:92:226996)\\n    at window.respondToMessage (<anonymous>:92:228381)\\n    at <anonymous>:1:8\", \"type\": \"Error\", \"code\": \"SDK_CANNOT_CONNECT_TO_API\"}, \"trace\": {\"id\": \"WCafKywXXC1eSLoJnDrRjY3XCQY6mrey\"}, \"transaction\": {\"id\": \"7ef4ace0-a7f8-499f-a9da-c6737023a351\"}, \"log\": {\"logger\": \"aggregate.client_logging\", \"origin\": {\"function\": \"log_obj\", \"file\": {\"line\": 43, \"name\": \"client_logging.py\"}}}, \"labels\": {\"task\": \"web\"}, \"process\": {\"pid\": 19}}","hash":"947b73c341ce365f6eb734ee2178de92ca8aad5e","_id":"coWP1vvljwjQfRad"}
{"createdAt":{"$$date":1617783819589},"type":"text","raw":" statusCode=429 content=b\\'\\\\n            { \"tppMessages\": [{\\\\n                    \"category\": \"ERROR\",\\\\n                    \"code\": \"ACCESS_EXCEEDED\",\\\\n                    \"text\": \"The access on the account has been exceeding the consented multiplicity without PSU involvement per day.\"\\\\n                    }]\\\\n            }\\\\n            \\''","hash":"9faf867896b850db1caf07ead2f49bc44ea1bca7","_id":"dpW2Tsu3cD0V6dY6"}
{"createdAt":{"$$date":1617717290221},"type":"text","raw":"aspsp-request-account-balances\\","hash":"9b36631b27d3b8d97ce13dffca18404b23f49f92","_id":"eztLVmYa1WzyGIHQ"}
{"createdAt":{"$$date":1617784780245},"type":"text","raw":"SophiaSaiada","hash":"c3192cdac3101d5e4af40dff38728e7573382843","_id":"gFrwdCiQ7s2lOtjt"}
{"createdAt":{"$$date":1617784089840},"type":"text","raw":"/xs2a/unpr/v1.0.5/accounts/55555_142/balances","hash":"4066adada0019d8893875d7b43c73a6f66665035","_id":"gqgsp57M95nQftij"}
{"createdAt":{"$$date":1617717085336},"type":"text","raw":"אני עדיין באותו מצב של ״רק היוזר עם החשבון האחד יכול להתחבר, כי השאר לוקח יותר מדי זמן״\n","hash":"44b0c380075b7e06738c44894ef8ba90e5df45e3","_id":"j0nBBJcwRJxAcXI5"}
{"createdAt":{"$$date":1617784208387},"type":"text","raw":"openbankingsb.poalim-api.co.il\\","hash":"215743bdc49fbafef2aedcfe84db192a283f7609","_id":"jjmrg0PKWiY0Njob"}
{"createdAt":{"$$date":1617784085814},"type":"text","raw":"'","hash":"bb589d0621e5472f470fa3425a234c74b1e202e8","_id":"k43mj7mpQrRvs09k"}
{"createdAt":{"$$date":1617783425743},"type":"text","raw":"+972 52-313-5232","hash":"9df2195f06d5629b213f58559d68e99ac8aae4f7","_id":"kfZHwfXZW9Vdsas1"}
{"createdAt":{"$$date":1617717218927},"type":"text","raw":"{\"@timestamp\": \"2021-04-06T15:01:06.037364\", \"event\": {\"action\": \"aspsp-request-oauth-token\", \"category\": \"process\", \"message\": \"Failed to replace code with token\", \"labels\": {\"application\": \"aggregate\", \"env\": \"server.settings\"}, \"kind\": \"event\"}, \"host\": {\"architecture\": \"x86_64\", \"kind\": \"host\"}, \"logline\": {\"level\": \"ERROR\", \"kind\": \"logline\"}, \"destination\": {\"domain\": \"openbankingsb.poalim-api.co.il\"}, \"network\": {\"direction\": \"egress\", \"protocol\": \"https\"}, \"url\": {\"domain\": \"openbankingsb.poalim-api.co.il\", \"original\": \"https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/oauth2/v1/token\", \"path\": \"/xs2a/unpr/oauth2/v1/token\", \"params\": \"\", \"port\": 19443}, \"trace\": {\"id\": null}, \"transaction\": {\"id\": \"2810ae80-3f50-4e60-88fc-7d58102b7a5e\"}, \"user\": {\"id\": null}, \"log\": {\"logger\": \"aggregate.auth_processes\", \"origin\": {\"function\": \"mark_auth_process_as_successful\", \"file\": {\"line\": 99, \"name\": \"auth_processes.py\"}}}, \"labels\": {\"task\": \"web\", \"aspsp\": \"12\"}, \"process\": {\"pid\": 21}, \"error\": {\"message\": \"AspspError: Request {'event.action': 'aspsp-request-oauth-token', 'span.id': 'b54d3c55-e8d6-4204-ab0c-149f54fe77bb', 'destination': {'domain': 'openbankingsb.poalim-api.co.il'}, 'network': {'direction': 'egress', 'protocol': 'https'}, 'url': {'domain': 'openbankingsb.poalim-api.co.il', 'original': 'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/oauth2/v1/token', 'path': '/xs2a/unpr/oauth2/v1/token', 'params': '', 'port': 19443}, 'http.request.method': 'POST'} to ASPSP 12 returned statusCode=None content=None\", \"type\": \"AspspError\", \"stack_trace\": \"  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 362, in _error_catcher\\n    yield\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 444, in read\\n    data = self._fp.read(amt)\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 458, in read\\n    n = self.readinto(b)\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 502, in readinto\\n    n = self.fp.readinto(b)\\n  File \\\"/usr/local/lib/python3.9/socket.py\\\", line 704, in readinto\\n    return self._sock.recv_into(b)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/gevent/_ssl3.py\\\", line 567, in recv_into\\n    return self.read(nbytes, buffer)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/gevent/_ssl3.py\\\", line 390, in read\\n    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 313, in gevent._gevent_c_hub_primitives._primitive_wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 314, in gevent._gevent_c_hub_primitives._primitive_wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_waiter.py\\\", line 154, in gevent._gevent_c_waiter.Waiter.get\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_gevent_c_greenlet_primitives.pxd\\\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch\\nsocket.timeout: The read operation timed out\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 750, in generate\\n    for chunk in self.raw.stream(chunk_size, decode_content=True):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 496, in stream\\n    data = self.read(amt=amt, decode_content=decode_content)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 461, in read\\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\\n  File \\\"/usr/local/lib/python3.9/contextlib.py\\\", line 135, in __exit__\\n    self.gen.throw(type, value, traceback)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/response.py\\\", line 367, in _error_catcher\\n    raise ReadTimeoutError(self._pool, None, 'Read timed out.')\\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 251, in make_aspsp_request\\n    res = _make_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 176, in _make_request\\n    res = request_func(url, timeout=ASPSP_REQUEST_TIMEOUT, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 581, in post\\n    return self.request('POST', url, data=data, json=json, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 533, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 686, in send\\n    r.content\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 828, in content\\n    self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/models.py\\\", line 757, in generate\\n    raise ConnectionError(e)\\nrequests.exceptions.ConnectionError: HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out.\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/src/server/aggregate/auth_processes.py\\\", line 95, in mark_auth_process_as_successful\\n    access_token = xs2a.consents.get_access_token(\\n  File \\\"/usr/src/server/aggregate/xs2a/consents.py\\\", line 164, in get_access_token\\n    res = fetch.make_aspsp_post_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 308, in make_aspsp_post_request\\n    return make_aspsp_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 263, in make_aspsp_request\\n    raise AspspError(aspsp_code, tag, req_logging_details, None, None) from e\\n\", \"cause\": {\"error\": {\"message\": \"HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out.\", \"type\": \"ConnectionError\"}}, \"code\": \"FAILED_TO_REPLACE_CODE_WITH_TOKEN\"}, \"span\": {\"id\": \"b54d3c55-e8d6-4204-ab0c-149f54fe77bb\"}, \"http\": {\"request\": {\"method\": \"POST\"}, \"response\": {\"status_code\": null, \"body\": {\"content\": null}}}}","hash":"d60781c51cf45a680e43ed492d54dfed41ecce4c","_id":"my2WtgcGMZ06G2TN"}
{"createdAt":{"$$date":1617784350952},"type":"text","raw":"55555_152","hash":"8e33e4b81151a8aba0cdb3971d34b2fdacffc0bb","_id":"ovr5BbDFhJKOv1gs"}
{"createdAt":{"$$date":1617784054680},"type":"text","raw":"name","hash":"6ae999552a0d2dca14d62e2bc8b764d377b1dd6c","_id":"q7UZI9YaDszIV2H1"}
{"createdAt":{"$$date":1617784745070},"type":"text","raw":"clipboard","hash":"e2ab8561c5a8f9967e62486c44211c63bcf7d002","_id":"tMTUvFQbfo8Rh1Ij"}
{"createdAt":{"$$date":1617716278585},"type":"text","raw":"attach_auth_process","hash":"af073d15ef3eb4c6cdce1b7576db550c97f44f1f","_id":"tlBNg5MBN8LofrqT"}
{"createdAt":{"$$date":1617784061724},"type":"text","raw":"{\"@timestamp\": \"2021-04-07T11:27:30.829299\", \"event\": {\"action\": \"aspsp-request-create-consent\", \"category\": \"process\", \"message\": \"Create consent error\", \"labels\": {\"application\": \"aggregate\", \"env\": \"server.settings\"}, \"kind\": \"event\"}, \"host\": {\"architecture\": \"x86_64\", \"kind\": \"host\"}, \"logline\": {\"level\": \"ERROR\", \"kind\": \"logline\"}, \"destination\": {\"domain\": \"openbankingsb.poalim-api.co.il\"}, \"network\": {\"direction\": \"egress\", \"protocol\": \"https\"}, \"url\": {\"domain\": \"openbankingsb.poalim-api.co.il\", \"original\": \"https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/consents\", \"path\": \"/xs2a/unpr/v1.0.5/consents\", \"params\": \"\", \"port\": 19443}, \"trace\": {\"id\": \"xZobMQIckhEQGz3pee8eoJd3UdTIDRjJ\"}, \"transaction\": {\"id\": \"c2313b99-e325-454b-8446-1cc60aabe99a\"}, \"user\": {\"id\": \"poa20\"}, \"log\": {\"logger\": \"aggregate.consents\", \"origin\": {\"function\": \"create_consents\", \"file\": {\"line\": 252, \"name\": \"consents.py\"}}}, \"labels\": {\"task\": \"web\", \"aspsp\": \"12\"}, \"process\": {\"pid\": 21}, \"error\": {\"message\": \"AspspError: Request {'event.action': 'aspsp-request-create-consent', 'span.id': '58426e0c-9e2a-40b7-b9f8-afd9d9bcd10f', 'destination': {'domain': 'openbankingsb.poalim-api.co.il'}, 'network': {'direction': 'egress', 'protocol': 'https'}, 'url': {'domain': 'openbankingsb.poalim-api.co.il', 'original': 'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/consents', 'path': '/xs2a/unpr/v1.0.5/consents', 'params': '', 'port': 19443}, 'http.request.method': 'POST'} to ASPSP 12 returned statusCode=None content=None\", \"type\": \"AspspError\", \"stack_trace\": \"  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 384, in _make_request\\n    six.raise_from(e, None)\\n  File \\\"<string>\\\", line 2, in raise_from\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 380, in _make_request\\n    httplib_response = conn.getresponse()\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 1347, in getresponse\\n    response.begin()\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 307, in begin\\n    version, status, reason = self._read_status()\\n  File \\\"/usr/local/lib/python3.9/http/client.py\\\", line 268, in _read_status\\n    line = str(self.fp.readline(_MAXLINE + 1), \\\"iso-8859-1\\\")\\n  File \\\"/usr/local/lib/python3.9/socket.py\\\", line 704, in readinto\\n    return self._sock.recv_into(b)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/gevent/_ssl3.py\\\", line 567, in recv_into\\n    return self.read(nbytes, buffer)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/gevent/_ssl3.py\\\", line 390, in read\\n    self._wait(self._read_event, timeout_exc=_SSLErrorReadTimeout)\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 317, in gevent._gevent_c_hub_primitives.wait_on_socket\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 322, in gevent._gevent_c_hub_primitives.wait_on_socket\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 313, in gevent._gevent_c_hub_primitives._primitive_wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 314, in gevent._gevent_c_hub_primitives._primitive_wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 46, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_hub_primitives.py\\\", line 55, in gevent._gevent_c_hub_primitives.WaitOperationsGreenlet.wait\\n  File \\\"src/gevent/_waiter.py\\\", line 154, in gevent._gevent_c_waiter.Waiter.get\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 61, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_greenlet_primitives.py\\\", line 65, in gevent._gevent_c_greenlet_primitives.SwitchOutGreenletWithLoop.switch\\n  File \\\"src/gevent/_gevent_c_greenlet_primitives.pxd\\\", line 35, in gevent._gevent_c_greenlet_primitives._greenlet_switch\\nsocket.timeout: The read operation timed out\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/adapters.py\\\", line 439, in send\\n    resp = conn.urlopen(\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 637, in urlopen\\n    retries = retries.increment(method, url, error=e, _pool=self,\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/util/retry.py\\\", line 368, in increment\\n    raise six.reraise(type(error), error, _stacktrace)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/packages/six.py\\\", line 686, in reraise\\n    raise value\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 597, in urlopen\\n    httplib_response = self._make_request(conn, method, url,\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 386, in _make_request\\n    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/urllib3/connectionpool.py\\\", line 306, in _raise_timeout\\n    raise ReadTimeoutError(self, url, \\\"Read timed out. (read timeout=%s)\\\" % timeout_value)\\nurllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out. (read timeout=10)\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 251, in make_aspsp_request\\n    res = _make_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 176, in _make_request\\n    res = request_func(url, timeout=ASPSP_REQUEST_TIMEOUT, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 581, in post\\n    return self.request('POST', url, data=data, json=json, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 533, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/sessions.py\\\", line 646, in send\\n    r = adapter.send(request, **kwargs)\\n  File \\\"/opt/venv/lib/python3.9/site-packages/requests/adapters.py\\\", line 529, in send\\n    raise ReadTimeout(e, request=request)\\nrequests.exceptions.ReadTimeout: HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out. (read timeout=10)\\n\\nThe above exception was the direct cause of the following exception:\\n\\nTraceback (most recent call last):\\n  File \\\"/usr/src/server/aggregate/consents.py\\\", line 238, in create_consents\\n    consent = create_consent(\\n  File \\\"/usr/src/server/aggregate/consents.py\\\", line 167, in create_consent\\n    return _create_consent(\\n  File \\\"/usr/src/server/aggregate/consents.py\\\", line 123, in _create_consent\\n    ) = xs2a.consents.create_consent_in_aspsp_get_resource_id_and_links(\\n  File \\\"/usr/src/server/aggregate/xs2a/consents.py\\\", line 50, in create_consent_in_aspsp_get_resource_id_and_links\\n    res = fetch.make_aspsp_post_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 308, in make_aspsp_post_request\\n    return make_aspsp_request(\\n  File \\\"/usr/src/server/aggregate/xs2a/fetch.py\\\", line 263, in make_aspsp_request\\n    raise AspspError(aspsp_code, tag, req_logging_details, None, None) from e\\n\", \"cause\": {\"error\": {\"message\": \"HTTPSConnectionPool(host='openbankingsb.poalim-api.co.il', port=19443): Read timed out. (read timeout=10)\", \"type\": \"ReadTimeout\"}}, \"code\": \"CREATE_CONSENT_ERROR\"}, \"span\": {\"id\": \"58426e0c-9e2a-40b7-b9f8-afd9d9bcd10f\"}, \"http\": {\"request\": {\"method\": \"POST\"}, \"response\": {\"status_code\": null, \"body\": {\"content\": null}}}}","hash":"d7b6520333c33a6650b9d327f47337d9029c3803","_id":"tzSqXOj2xtDudOtv"}
{"createdAt":{"$$date":1617784693510},"type":"text","raw":"deployment.apps/backend-deployment","hash":"9ff063d9f2f55ed6ac6e913d4a9e6e7e2c852f27","_id":"vS3wdX3ZIfDGfbsf"}
{"createdAt":{"$$date":1617716549793},"type":"text","raw":"SN=2563B300FA8AC46D092FEA72BCA722BC491E1BA6,CA=CN=Test-OpenBankingIL Seal CA,OU=GCIO-eGOV-OBCA,2.5.4.97=NTRIL-50010037,O=Government Of Israel,C=IL","hash":"d5bf61f08c2ec4f15a9751ca3629a807248b5f15","_id":"wUvKau1DnXO8wC9D"}
{"createdAt":{"$$date":1617716414162},"type":"text","raw":"Digest","hash":"47fdd58bee4dc86df2b978107102a22b9c44345b","_id":"wqnqeNml35aEbyMn"}
{"createdAt":{"$$date":1617717322382},"type":"text","raw":"content=b\\'\\\\n            { \"tppMessages\": [{\\\\n                    \"category\": \"ERROR\",\\\\n                    \"code\": \"ACCESS_EXCEEDED\",\\\\n                    \"text\": \"The access on the account has been exceeding the consented multiplicity without PSU involvement per day.\"\\\\n                    }]\\\\n            }\\\\n            \\'')\n\n","hash":"01ea0f2c531e123da394029f07f28e5175bf0057","_id":"xGh5FbySHZdXfXrK"}
{"createdAt":{"$$date":1617717291231},"type":"text","raw":"Message: AspspError('AspspError: Request {\\'event.action\\': \\'aspsp-request-account-balances\\', \\'span.id\\': \\'1f9d3a5d-24c2-426f-aabb-638c6258296f\\', \\'destination\\': {\\'domain\\': \\'openbankingsb.poalim-api.co.il\\'}, \\'network\\': {\\'direction\\': \\'egress\\', \\'protocol\\': \\'https\\'}, \\'url\\': {\\'domain\\': \\'openbankingsb.poalim-api.co.il\\', \\'original\\': \\'https://openbankingsb.poalim-api.co.il:19443/xs2a/unpr/v1.0.5/accounts/22222_5/balances\\', \\'path\\': \\'/xs2a/unpr/v1.0.5/accounts/22222_5/balances\\', \\'params\\': \\'\\', \\'port\\': 19443}, \\'http.request.method\\': \\'GET\\'} to ASPSP 12 returned statusCode=429 content=b\\'\\\\n            { \"tppMessages\": [{\\\\n                    \"category\": \"ERROR\",\\\\n                    \"code\": \"ACCESS_EXCEEDED\",\\\\n                    \"text\": \"The access on the account has been exceeding the consented multiplicity without PSU involvement per day.\"\\\\n                    }]\\\\n            }\\\\n            \\'')","hash":"8a71f0f7a5915778b802e8137da406766dda84af","_id":"xY7oEbacwo2jgb8C"}
{"createdAt":{"$$date":1617784113952},"type":"text","raw":"stack_trace","hash":"f8e1f2477510ff003a97faae113980f1275864eb","_id":"zHaLPrfLG5p5Ost4"}
{"createdAt":{"$$date":1617784828239},"type":"text","raw":"SophiaSaiada","hash":"c3192cdac3101d5e4af40dff38728e7573382843","_id":"gFrwdCiQ7s2lOtjt"}
